### ISSUE TITLE
Errors from server.py

### ISSUE THREAD

**Issue by kd8bxp** [adeept/Adeept_PiCar-A#3]
I get the following errors when I start the server.py app.

waiting for connection...
('...connected from :', ('192.168.1.15', 51570))
start recording
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "server.py", line 136, in video_net
    connection.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

192.168.1.15
start thread
start recording
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "server.py", line 136, in video_net
    connection.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

running the current version of Raspbian Stretch with desktop and recommended sofware (Nove 2018), updated, and rebooted many times. I'm not sure how to fix this issue.

**Comment by fallart** [comment]
u have some errors in client.
i had this problem when i tried to run the client on linux. (on linux you must create "ip.txt" and "vlc.txt")

**Comment by kd8bxp** [comment]
I have no problem running the client, both files you suggest are present, can you share your vlc.txt file, there maybe a problem with mine ? I am able to run the client, and even able to control the car, but I do get the above errors in the server no matter what I seem to do.

**Comment by fallart** [comment]
i had "IP.txt" and it doesnt work on linux, i have just copied the file and named "ip.txt" 
i still have "error: [Errno 32] Broken pipe", bur i can control the car. only the camera doesnt work

**Comment by kd8bxp** [comment]
I'll probably end up adapting the web sharing video code, and drive from the Waveshare AlphaBot, 
https://www.waveshare.com/wiki/AlphaBot
It works, is web base, so no need for client software - and I've used it on a couple of raspberry pi bots in the past, was just hoping there was an answer to the server.py issue. 
I just need to find the time to sit down and make the changes needed.

**Comment by fallart** [comment]
i will fix this error today i hope
the problem is that server tries connect to clients websocket before client open them
its hard to explain with my english... i hope you can understand me :D
